### ISSUE TITLE
OBS 28 Version

### ISSUE THREAD

**Issue by XSilverlink** [DigitOtter/obs_scene_tree_view#12]
Hey mate,

OBS 28 just dropped, any plans on updating it for obs 28 as well?
Love this plugin and would be a shame to lose it 😀

**Comment by veka-server** [comment]
same here :)

**Comment by Geredeth** [comment]
Yup, same. This is my favorite plug-in. It's something OBS should buy and integrate into the default system, it's really a pain without it.

**Comment by acelgasdf** [comment]
Hello, just to ask the same as the rest. This is the BEST plugin

**Comment by DigitOtter** [comment]
I just updated the plugin to work with OBS 28. Let me know if there are any issues :)

**Comment by XSilverlink** [comment]
Seems to be working! Thank you very much :)
