### ISSUE TITLE
Buttons are not aligned and do not hide using the global settings

### ISSUE THREAD

**Issue by Laurox** [DigitOtter/obs_scene_tree_view#13]
### **Operating System Info**
Windows 10

### **OBS Studio Version**
28.0.1

### **Plugin Version**
v0.1.4

---

# Issue
The UI Buttons are not aligned correctly in the newest OBS Version compared to standard Scene / Source View (screenshots attached), and do not hide when the **Scene/Source List Buttons** Settings (under the menu **View**) is disabled.
Interacting is still possible using the Right Click Context Menu.

### Current Shown Buttons
![grafik](https://user-images.githubusercontent.com/50633486/188479546-9124aeee-f7dd-41ff-8abb-44df378c5458.png)

### Expected Shown Buttons
![grafik](https://user-images.githubusercontent.com/50633486/188479518-27734052-969c-448e-b509-8789d79c4aee.png)

### Current Hidden Buttons
![grafik](https://user-images.githubusercontent.com/50633486/188480062-139dc7c3-1cd1-4fae-b9ca-a2b6dfb49655.png)

### Excpected Hidden Buttons
![grafik](https://user-images.githubusercontent.com/50633486/188480004-e6c12bcd-8794-46f9-94a8-ebdab937ba7f.png)

**Comment by DigitOtter** [comment]
The buttons will now be hidden accordingly and they should be aligned similarly to the scenes tab
