### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by patrick91** [DigitOtter/obs_scene_tree_view#14]
Hi there :) Would be possible to get a mac version of this plugin? 😊

I can try to help with setting CI :)

**Comment by DigitOtter** [comment]
Hi, unfortunately, I don't have a Mac to build and debug the plugin. If you want, you can try and get it up and running on macOS :)

**Comment by devxan** [comment]
@patrick91 could you try to help get a functional MacOS version of the plugin?

**Comment by Celldweller43** [comment]
I second this 👍🏻  I'm using OBS for recording training videos for my company, and I'm using a Mac.  I think it would be very helpful to be able to organize my scenes into folders.
