### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by AdrianJC73** [DigitOtter/obs_scene_tree_view#15]
After installing the "obs_scene_tree_view.dll" - file twice, watching two different video's on installing it doesn't work.
When starting OBS Studio after the installation of this plugin nothing happens, no new screen or popup, nothing happens......

**Comment by AdrianJC73** [comment]
Hi me again, version 0.14, isn't working on OBS-Studio 27.... 
I have installed the older version 0.13 in OBS-Studio 27 and now its working.

**Comment by DigitOtter** [comment]
Yes, when updating to version 28, OBS switched from using Qt5 to Qt6. The newer obs_scene_tree_view is also compiled with Qt6, so it is no longer compatible with OBS 27
