### ISSUE TITLE
obs crashes on windows. 

### ISSUE THREAD

**Issue by moonkehh** [DigitOtter/obs_scene_tree_view#16]
I went to the obs discord and I uploaded a file to it, and they said scene tree is the reason why its happening. I am uploading it now to to you guys to check out before deleting it and retrying it. I do not want to mess with the orginization because it took forever to do. 
[Crash 2022-09-20 09-08-12.txt](https://github.com/DigitOtter/obs_scene_tree_view/files/9608452/Crash.2022-09-20.09-08-12.txt)

**Comment by moonkehh** [comment]
Also if you need me to do anything with this or talk to them I wish to help resolve this so in the future this doesnt happen anymore. Thank you for creating this plugin.

**Comment by DigitOtter** [comment]
Hi,
Which version of SceneTree are you using? The newest SceneTree version (v0.1.4) is built for OBS 28.

I see you're using OBS 27, could you try upgrading to OBS 28?
Alternatively, could you try using SceneTree v0.1.3  with OBS 27 and let me know if it still crashes?
