### ISSUE TITLE
No folder icon 

### ISSUE THREAD

**Issue by Delirya** [DigitOtter/obs_scene_tree_view#17]
Heya. Installed the update to this today, into OBS 28.0.3 and I'm not seeing any folder icon in my scene window.

I unzipped the package directly into the obs-studio folder, and I can see that everything is where it ought to be within their respective folders. 

I downloaded obs studio and ran the installer again, just in case Id lost something, but no change.

I do have the stream elements live (SELive 22.9.8.69) installed too, would that be the cause?

**Comment by DigitOtter** [comment]
Hi, if you right-click on a folder, it should show an option to toggle folder-icons. What happens if you click it?

**Comment by Delirya** [comment]
I dont have any folder icon at all 
![Screen Shot 10-20-22 at 12 59 PM](https://user-images.githubusercontent.com/42555594/197012332-3ec948f9-76a8-405a-8bc8-0ad5e00abed5.PNG)

**Comment by Delirya** [comment]
Oh no.. im a muppet. I'm so sorry, I just didnt have the dock open. My apologies for wasting your time! <3
