### ISSUE TITLE
[Suggestion] Add icons to the list

### ISSUE THREAD

**Issue by XSilverlink** [DigitOtter/obs_scene_tree_view#3]
I don't know if this area will be used for suggestions, but here is one anyway ;)

Is it possible to maybe add an icon to the scene names?
Maybe use the icon that OBS already uses when you use scene nesting?

So it would look something like this:
![](https://i.imgur.com/ooPbGYQ.png)

Thanks for the awesome plugin 😄

**Comment by XSilverlink** [comment]
Love it! But now it kinda also needs a folder icon of some sort for the folders. I don't know if that is possible. If it's not possible its perfect :)

**Comment by XSilverlink** [comment]
Never mind, I just figured out that you can right click a folder and enable them! You're awesome dude!

I may have another suggestion, but if you want me to add another issue / request I will separate it.
Is it possible that you add an "Add Folder" to the right click menu. Now I do right click and press add and it adds a scene instead of a folder ;)

Thank you so far :D Pretty awesome!

**Comment by DigitOtter** [comment]
Great! :)
Yes, having an additional right-click option for adding folders makes sense.

**Comment by DigitOtter** [comment]
I've added the option and updated the zip file :)

**Comment by XSilverlink** [comment]
Looks awesome mate :D
