### ISSUE TITLE
[Suggestion] Remember which folders you have expanded

### ISSUE THREAD

**Issue by Netrex** [DigitOtter/obs_scene_tree_view#4]
Hello. First of all thanks for this amazing plugin. Been looking for something like this for a while so it's awesome to see it finally here

I've noticed that if you expand multiple folders in SceneTree and then proceed to restart OBS, those expanded folders will now all be closed with only the active scene folder being expanded. Would it be possible to make SceneTree remember which folders are expanded at all times for organizing's sake?

Thank you

**Comment by DigitOtter** [comment]
Thanks! It makes sense, I've updated the code and zip file
