### ISSUE TITLE
Renaming/Duplicating scene collections

### ISSUE THREAD

**Issue by MP5Squeaky** [DigitOtter/obs_scene_tree_view#6]
Renaming or duplicating a scene collection doesn't copy the existing folder structure to the new group in scene_tree.json.

**Comment by DigitOtter** [comment]
Thanks, I'm aware of the issue. However, to implement a fix, I require an event notification from obs that is missing, even though it's listed in the documentation (see https://github.com/obsproject/obs-studio/issues/6517).

I can implement a fix on the next version of obs, once the notification has been added. Until then, you can try manually changing the file with the tree data. I've added instructions at https://obsproject.com/forum/threads/scene-tree-folder-plugin-for-obs-studio.155180/post-572974

**Comment by DigitOtter** [comment]
With OBS 28, folder structure can now be preserved over scene collection renames.
