### ISSUE TITLE
Click to switch scene registers twice

### ISSUE THREAD

**Issue by ysaxa** [DigitOtter/obs_scene_tree_view#7]
When clicking a scene (not the active one), the scene switches both on mouse button press and on mouse button release (hence twice for every click).
This is not visible when the transition is cut/fade/move but it is very visible with a stinger because the video restarts every time which is not desirable.

**Comment by DigitOtter** [comment]
Thanks for the info, the issue should be fixed now.

Let me know if the problem persists.

**Comment by ysaxa** [comment]
Yes, everything seems fine now, thanks for the quick fix 😄
